import { Roboto } from "next/font/google";
import "./globals.css";

import ThreeDCard from "@/components/threeDCard";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
          <body
            className={`${roboto.variable} antialiased`}
            >
            <ThreeDCard/>
            <main className="content">
              {children}
            </main>
          </body>
      </html>
  );
}
